### PR TITLE
Water models Lab integration

### PR DESCRIPTION
**Pull request by pjanik**
Adds integration with Lab framework. Examples that already use it (I've pushed those changes to agentscript-models-dev gh-pages):
http://lab.concord.org/interactives.html#interactives/water/water-1.json
http://lab.concord.org/interactives.html#interactives/water/water-3.json
http://lab.concord.org/interactives.html#interactives/water/water-7.json

### CODE REVIEW

**Comment by scytacki** [comment]
I don't have time for a full review, but from a high level:

Since the lab integration file seems very similar to the lab-integration file used in other places of the repository. Can you come up with a way to share the common parts? Or is that not worth it in this case?

**Comment by pjanik** [comment]
Hm, those files have very similar structure and a few common, tiny helpers (`registerModelFunc`, `registerCustomFunc`), but rest of the code is model specific (mainly names of properties and methods). Of course we could implement some fancy wrapper and provide that information using nicer structure, but frankly speaking I don't think it's worth it here. Probably we won't make the code significantly shorter, but we will add one layer of abstraction which can make integration more obscure. At the moment we use `iframePhone` directly, so it's easy to understand what's going on and how this works (I hope so).

**Comment by scytacki** [comment]
That makes sense. I didn't look very closely. @psndcsrv can you take a look at this one since you've done much of the agent script integration in the past?

**Comment by pjanik** [comment]
Two new commits here. I've added support of drawing palette. Actually, I've reused existing buttons, but added autoscaling, changed layout and other necessary tweaks. Controls logic is pretty coupled to DOM elements, so recreating them would be a bit painful. We had demo today and I think Sarah was fine with it. Example:
http://lab.concord.org/interactives.html#interactives/water/water-4.json

**Comment by psndcsrv** [comment]
This all looks good to me!

**Pull request merged**
